windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAAAAAAAAAAB38AAAQeAAAAAwAAAAMAAAd8AAAEGwAAAAAAAAAAB4AAAAADAAAA
    AwAAB3wAAAQb
  tabs:
  - history:
    - active: true
      last_visited: '2021-04-22T08:32:45'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'Mini review: The Acme editor on Debian on Windows - DonationCoder.com'
      url: https://www.donationcoder.com/forum/index.php?topic=45547.0
      zoom: 1.3
  - history:
    - active: true
      last_visited: '2021-04-22T08:32:45'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: How to use Ansible synchronization GitHub - Programmer Sought
      url: https://www.programmersought.com/article/55592782551/
      zoom: 1.3
  - history:
    - active: true
      last_visited: '2021-04-22T08:32:45'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: voco/INSTALL.md at master · lyncisdev/voco
      url: https://github.com/lyncisdev/voco/blob/master/INSTALL.md
      zoom: 1.3
  - history:
    - active: true
      last_visited: '2021-04-22T08:32:45'
      pinned: false
      scroll-pos:
        x: 0
        y: 1471
      title: python - How to schedule and cancel tasks with asyncio - Stack Overflow
      url: https://stackoverflow.com/questions/40016501/how-to-schedule-and-cancel-tasks-with-asyncio#:~:text=In%20other%20words%2C%20just%20pass,you%20need%20to%20stop%20it.
      zoom: 1.3
  - history:
    - active: true
      last_visited: '2021-04-22T08:32:45'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Actions sub-package — Dragonfly 0.30.1 documentation
      url: https://dragonfly2.readthedocs.io/en/latest/actions.html
      zoom: 1.3
  - history:
    - active: true
      last_visited: '2021-04-22T08:32:45'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Paravirtualization - Wikipedia
      url: https://en.wikipedia.org/wiki/Paravirtualization
      zoom: 1.3
  - history:
    - active: true
      last_visited: '2021-04-22T08:32:45'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Why you should use named pipes on Linux | Network World
      url: https://www.networkworld.com/article/3251853/why-use-named-pipes-on-linux.html
      zoom: 1.3
  - active: true
    history:
    - active: true
      last_visited: '2021-04-22T10:25:44'
      pinned: false
      scroll-pos:
        x: 0
        y: 12199
      title: Getting Started with Voice Driven Development - whale quench
      url: https://whalequench.club/blog/2019/09/03/learning-to-speak-code.html
      zoom: 1.3
