windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAV4AAAAAAAADPcAAAQeAAAFewAAAAMAAAz0AAAEGwAAAAIAAAAAB4AAAAV7AAAA
    AwAADPQAAAQb
  tabs:
  - history:
    - active: true
      last_visited: '2021-02-28T14:06:53'
      pinned: false
      scroll-pos:
        x: 0
        y: 4426
      title: (41) vocaloid - YouTube
      url: https://www.youtube.com/results?search_query=vocaloid&sp=EgIYAg%253D%253D
      zoom: 1.3
  - history:
    - active: true
      last_visited: '2021-02-28T14:06:53'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Identity-management system - Wikipedia
      url: https://en.wikipedia.org/wiki/Identity-management_system
      zoom: 1.3
  - history:
    - active: true
      last_visited: '2021-02-28T14:06:53'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Directory service - Wikipedia
      url: https://en.wikipedia.org/wiki/Directory_service
      zoom: 1.3
  - history:
    - active: true
      last_visited: '2021-02-28T14:06:53'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Difference between Active directory and Identity and Access managment
        - Stack Overflow
      url: https://stackoverflow.com/questions/43987531/difference-between-active-directory-and-identity-and-access-managment
      zoom: 1.3
  - history:
    - active: true
      last_visited: '2021-02-28T14:06:54'
      pinned: false
      scroll-pos:
        x: 0
        y: 676
      title: dns zone - Google Search
      url: https://www.google.com/search?q=dns%20zone
      zoom: 1.3
  - active: true
    history:
    - active: true
      last_visited: '2021-02-28T14:08:51'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: DNS zone - Wikipedia
      url: https://en.wikipedia.org/wiki/DNS_zone
      zoom: 1.3
