windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAAAAAAAAAAB38AAAQeAAAAAwAAAAMAAAd8AAAEGwAAAAAAAAAAB4AAAAADAAAA
    AwAAB3wAAAQb
  tabs:
  - history:
    - active: true
      last_visited: '2021-07-19T03:05:28'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Anime Amino
      url: https://aminoapps.com/c/anime/page/item/mubong-park-bagmubong/jPto_IGomkgGr4zg420wvwVkgRVGN
      zoom: 1.3
  - history:
    - active: true
      last_visited: '2021-07-19T03:05:25'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Utaite | Utaite Wiki | Fandom
      url: https://utaite.fandom.com/wiki/Utaite
      zoom: 1.3
  - history:
    - active: true
      last_visited: '2021-07-19T03:05:28'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: aspiring utaites - Google Search
      url: https://www.google.com/search?q=aspiring+utaites&sxsrf=ALeKk02aJ6AuwfHkUW5oZ9d4i7WWV4NCqA%3A1622184199369&ei=B5GwYOfvFcitrgSR0I6AAg&oq=aspiring+utaites&gs_lcp=Cgdnd3Mtd2l6EAMyBQghEKABOgQIIxAnOgQIABBDOgIIADoECAAQCjoECC4QCjoHCCMQsAIQJzoGCAAQDRAKOgQIABANOgYIABANEB46CAgAEA0QChAeOgYIABAHEB46CAgAEAcQChAeOgoIABAIEAcQChAeUL0WWPfsAWCw8QFoAXACeAGAAecBiAGuDJIBBjEwLjQuMZgBAKABAaoBB2d3cy13aXrAAQE&sclient=gws-wiz&ved=0ahUKEwinj9qH4-vwAhXIlosKHRGoAyAQ4dUDCA4&uact=5
      zoom: 1.3
  - history:
    - active: true
      last_visited: '2021-07-19T03:05:25'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Who is your favorite Utaite? - Quora
      url: https://www.quora.com/Who-is-your-favorite-Utaite
      zoom: 1.3
  - history:
    - active: true
      last_visited: '2021-07-19T03:05:26'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Manage your dotfiles with Ansible | by Kyle Espinola | Espinola Designs
        | Medium
      url: https://medium.com/espinola-designs/manage-your-dotfiles-with-ansible-6dbedd5532bb
      zoom: 1.3
  - history:
    - active: true
      last_visited: '2021-07-19T03:05:25'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'Patterns: targeting hosts and groups — Ansible Documentation'
      url: https://docs.ansible.com/ansible/latest/user_guide/intro_patterns.html
      zoom: 1.3
  - history:
    - active: true
      last_visited: '2021-07-19T03:05:26'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: WaniKani, a kanji learning application by Tofugu
      url: https://www.wanikani.com/#explanation
      zoom: 1.3
  - active: true
    history:
    - active: true
      last_visited: '2021-07-19T03:05:26'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'kubernetes-up-and-running/kuard: Demo app for Kubernetes Up and Running
        book'
      url: https://github.com/kubernetes-up-and-running/kuard
      zoom: 1.3
