windows:
- active: true
  geometry: !!binary |
    AdnQywACAAAAAAUAAAAAAAAADH8AAAQfAAAFAwAAAAMAAAx8AAAEHAAAAAIAAAAAB4A=
  tabs:
  - history:
    - last_visited: '2020-10-26T16:48:23'
      pinned: false
      title: DuckDuckGo — Privacy, simplified.
      url: https://start.duckduckgo.com/
    - active: true
      last_visited: '2020-10-26T01:04:45'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: History
      url: qute://history/
      zoom: 1.0
  - history:
    - last_visited: '2020-10-26T01:12:03'
      pinned: false
      title: vim difference between imap and inoremap - Google Search
      url: https://www.google.com/search?q=vim%20difference%20between%20imap%20and%20inoremap
    - active: true
      last_visited: '2020-10-26T01:15:32'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: tiddlywiki codemirror vimrc - Google Search
      url: https://www.google.com/search?sxsrf=ALeKk02Qw-vP07OUTh4v0d_yakCG5r2Rfg%3A1603663922633&ei=MviVX6GQJq3qrgSogbtI&q=tiddlywiki+codemirror+vimrc&oq=tiddlywiki+codemirror+vimrc&gs_lcp=CgZwc3ktYWIQAzIJCAAQyQMQFhAeOgcIIxDqAhAnOgcILhDqAhAnOgQIIxAnOgUIABDJAzoCCAA6CAgAEMkDEJECOgUIABCRAjoECAAQQzoICC4QxwEQrwE6AgguOgQIABAKOgcIABAUEIcCOgoIABDJAxAUEIcCOgYIABAWEB5Q8uILWNrQDGCm0wxoAnABeACAAdAEiAH8J5IBCjAuMjQuNC0yLjKYAQCgAQGqAQdnd3Mtd2l6sAEKwAEB&sclient=psy-ab&ved=0ahUKEwih8cnT4dDsAhUttYsKHajADgkQ4dUDCA0&uact=5
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-10-26T01:23:25'
      pinned: false
      scroll-pos:
        x: 0
        y: 101
      title: My ~TiddlyWiki — a non-linear personal web notebook
      url: http://127.0.0.1:8081/
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-10-26T02:04:40'
      pinned: false
      scroll-pos:
        x: 0
        y: 826
      title: 'How to create keyboard shortcuts: TiddlyWiki — a non-linear personal
        web notebook'
      url: https://tiddlywiki.com/static/How%2520to%2520create%2520keyboard%2520shortcuts.html
      zoom: 1.0
    - last_visited: '2020-10-25T12:52:24'
      pinned: false
      title: 'keyboard: TiddlyWiki — a non-linear personal web notebook'
      url: https://tiddlywiki.com/static/KeyboardWidget.html
    - last_visited: '2020-10-25T12:38:32'
      pinned: false
      title: 'ActionWidgets: TiddlyWiki — a non-linear personal web notebook'
      url: https://tiddlywiki.com/static/ActionWidgets.html
  - history:
    - active: true
      last_visited: '2020-10-26T02:30:27'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: simple spreadsheet in javascript - Google Search
      url: https://www.google.com/search?q=simple%20spreadsheet%20in%20javascript
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-10-26T02:34:15'
      pinned: false
      scroll-pos:
        x: 0
        y: 2024
      title: Mithril
      url: https://lhorie.github.io/mithril-blog/a-spreadsheet-in-60-lines-of-javascript.html
      zoom: 1.75
  - history:
    - active: true
      last_visited: '2020-10-26T03:23:53'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: mithril vs react - Google Search
      url: https://www.google.com/search?q=mithril%20vs%20react
      zoom: 1.0
  - active: true
    history:
    - active: true
      last_visited: '2020-10-26T03:24:57'
      original-url: https://www.youtube.com/search?q=mithril%20js
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: (77) mithril js - YouTube
      url: https://www.youtube.com/results?q=mithril+js
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-10-26T03:23:57'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Framework comparison - Mithril.js
      url: https://mithril.js.org/framework-comparison.html
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-10-26T03:25:24'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: what does pragmatic mean in programming - Google Search
      url: https://www.google.com/search?q=what%20does%20pragmatic%20mean%20in%20programming
      zoom: 1.0
  - history:
    - last_visited: '2020-10-26T03:11:17'
      pinned: false
      title: javascript m() - Google Search
      url: https://www.google.com/search?q=javascript%20m%28%29
    - active: true
      last_visited: '2020-10-26T03:11:19'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: m(selector, attributes, children) - Mithril.js
      url: https://mithril.js.org/hyperscript.html
      zoom: 1.0
  - history:
    - last_visited: '2020-10-26T02:53:36'
      pinned: false
      title: isNaN(+value) javascript - Google Search
      url: https://www.google.com/search?q=isNaN%28%2Bvalue%29%20javascript
    - active: true
      last_visited: '2020-10-26T02:53:51'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: isNaN(+value) javascript - Google Search
      url: https://www.google.com/search?q=isNaN(%2Bvalue)+javascript&sxsrf=ALeKk023zzQ3iOkd9ksXYJPsShDTY8TRUQ:1603670016004&ei=_w-WX8j0PIiorgSezDc&start=10&sa=N&ved=2ahUKEwiI8I-t-NDsAhUIlIsKHR7mDQAQ8tMDegQIGxAv&biw=1914&bih=1014
      zoom: 1.0
  - history:
    - last_visited: '2020-10-26T02:42:53'
      pinned: false
      title: mithril - Google Search
      url: https://www.google.com/search?q=mithril
    - last_visited: '2020-10-26T02:42:58'
      pinned: false
      title: Mithril - Wikipedia
      url: https://en.wikipedia.org/wiki/Mithril
    - active: true
      last_visited: '2020-10-26T02:43:04'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Mithril (disambiguation) - Wikipedia
      url: https://en.wikipedia.org/wiki/Mithril_(disambiguation)
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-10-26T02:43:22'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: mithril js - Google Search
      url: https://www.google.com/search?q=mithril%20js
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-10-26T02:43:34'
      pinned: false
      scroll-pos:
        x: 0
        y: 1980
      title: 'MithrilJS/mithril.js: A JavaScript Framework for Building Brilliant
        Applications'
      url: https://github.com/MithrilJS/mithril.js/
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-10-26T02:43:28'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Introduction - Mithril.js
      url: https://mithril.js.org/
      zoom: 1.0
  - history:
    - last_visited: '2020-10-26T02:38:50'
      pinned: false
      title: Tiny Excel-like app in vanilla JS - JSFiddle - Code Playground
      url: http://jsfiddle.net/ondras/hYfN3/
    - active: true
      last_visited: '2020-10-26T02:39:07'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Tiny Excel-like app in vanilla JS - JSFiddle - Code Playground
      url: http://jsfiddle.net/ondras/hYfN3/
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-10-26T01:04:51'
      pinned: false
      scroll-pos:
        x: 0
        y: 40
      title: Useful custom Qutebrowser keybindings | Samuel Walladge
      url: https://www.swalladge.net/archives/2017/07/31/qutebrowser-keybindings/
      zoom: 1.0
- geometry: !!binary |
    AdnQywACAAAAAAUAAAAAAAAADH8AAAQfAAAFAwAAAAMAAAx8AAAEHAAAAAIAAAAAB4A=
  tabs:
  - active: true
    history:
    - active: true
      last_visited: '2020-10-26T02:34:43'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: (77) Jordan Peterson Reveals How to Sell Anything to Anyone - YouTube
      url: https://www.youtube.com/watch?v=89Vpqm2IaPE
      zoom: 1.0
