windows:
- active: true
  geometry: !!binary |
    AdnQywACAAAAAAeAAAAAAAAADv8AAAQfAAAHgwAAAAMAAA78AAAEHAAAAAEAAAAAB4A=
  tabs:
  - history:
    - last_visited: '2020-10-19T08:43:18'
      pinned: false
      title: Xwrits Manual
      url: http://www.lcdf.org/xwrits/man.html
    - last_visited: '2020-10-19T09:16:06'
      pinned: false
      title: History
      url: qute://history/
    - last_visited: '2020-10-14T21:18:15'
      pinned: false
      title: Build A Calculator With JavaScript Tutorial - YouTube
      url: https://www.youtube.com/watch?v=j59qQ7YWLxw&feature=youtu.be
    - last_visited: '2020-10-14T21:18:15'
      pinned: false
      title: Build A Clock With JavaScript - YouTube
      url: https://www.youtube.com/watch?v=Ki0XXrlKlHY
    - last_visited: '2020-10-14T21:35:59'
      pinned: false
      title: Build Tic Tac Toe With JavaScript - Tutorial - YouTube
      url: https://www.youtube.com/watch?v=Y-GkMjUZsmM
    - last_visited: '2020-10-14T22:18:06'
      pinned: false
      title: Learn JavaScript - Full Course for Beginners - YouTube
      url: https://www.youtube.com/watch?v=PkZNo7MFNFg
    - active: true
      last_visited: '2020-10-15T00:14:53'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: (68) Intro to Java Programming - Course for Absolute Beginners - YouTube
      url: https://www.youtube.com/watch?v=GoXwIVyNvX0
      zoom: 1.0
  - active: true
    history:
    - active: true
      last_visited: '2020-10-15T05:20:54'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: as in case - Google Search
      url: https://www.google.com/search?q=as%20in%20case
      zoom: 1.0
  - history:
    - last_visited: '2020-10-15T05:21:46'
      pinned: false
      title: Google Translate
      url: https://translate.google.com/#view=home&op=translate&sl=ru&tl=en&text=%D0%BA%D0%B0%D0%BA%20%D0%B8%20%D0%B2%20%D0%BF%D1%80%D0%BE%D1%88%D0%BB%D0%BE%D0%BC%20%D1%81%D0%BB%D1%83%D1%87%D0%B0%D0%B5
    - last_visited: '2020-10-15T05:22:29'
      original-url: https://translate.google.com/#view=home&op=translate&sl=ru&tl=en&text=%D0%BA%D0%B0%D0%BA%20%D0%B8%20%D0%B2%20%D0%BF%D1%80%D0%BE%D1%88%D0%BB%D0%BE
      pinned: false
      title: Google Translate
      url: https://translate.google.com/#view=home&op=translate&sl=ru&tl=en&text=%D0%BA%D0%B0%D0%BA%20%D0%B8%20%D0%B2%20%D0%BF%D1%80%D0%BE%D1%88%D0%BB%D0%BE%D1%8B%D0%B9%20%D1%80%D0%B0%D0%B7
    - last_visited: '2020-10-15T05:22:36'
      original-url: https://translate.google.com/#view=home&op=translate&sl=ru&tl=en&text=%D0%BA%D0%B0%D0%BA%20%D0%B8%20%D0%B2%20%D0%BF%D1%80%D0%BE%D1%88%D0%BB%D0%BE%D1%8B%D0%B9
      pinned: false
      title: Google Translate
      url: https://translate.google.com/#view=home&op=translate&sl=ru&tl=en&text=%D0%BA%D0%B0%D0%BA%20%D0%B8%20%D0%B2%20%D0%BF%D1%80%D0%BE
    - last_visited: '2020-10-15T05:22:38'
      pinned: false
      title: Google Translate
      url: https://translate.google.com/#view=home&op=translate&sl=ru&tl=en&text=%D0%BA
    - last_visited: '2020-10-15T05:22:50'
      pinned: false
      title: Google Translate
      url: https://translate.google.com/#view=home&op=translate&sl=ru&tl=en&text=h
    - active: true
      last_visited: '2020-10-15T05:25:43'
      original-url: https://translate.google.com/#view=home&op=translate&sl=ru&tl=en&text=%D0%BF%D1%80
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Google Translate
      url: https://translate.google.com/#view=home&op=translate&sl=ru&tl=en&text=%D0%BF%D1%80%D0%B8%D1%81%D0%BF%D0%BE%D1%81%D0%BE%D0%B1%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%BF%D1%80%D0%B5%D0%B4%D0%BD%D0%B0%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%BE%20%D0%B4%D0%BB%D1%8F
      zoom: 1.0
  - history:
    - last_visited: '2020-10-15T05:26:20'
      pinned: false
      title: is intended to - Google Search
      url: https://www.google.com/search?q=is%20intended%20to
    - last_visited: '2020-10-15T05:27:54'
      pinned: false
      title: improve the robustness - Google Search
      url: https://www.google.com/search?sxsrf=ALeKk00BwOeXFb4KayB3miQ_3zVfhUpetw%3A1602728779767&ei=S7OHX92VLsGIrwSzvbTYBA&q=improve+the+robustness&oq=improve+the+robustness&gs_lcp=CgZwc3ktYWIQAzIJCAAQyQMQFhAeMgYIABAWEB4yBggAEBYQHjoKCCMQsAIQyQMQJzoECAAQDToHCCMQ6gIQJzoECCMQJzoFCAAQyQM6AggAOggILhDHARCjAjoICAAQyQMQkQI6BQgAEJECOggILhDHARCvAToCCC46CAgAEBYQChAeUOv1BFiuzgVguNkFaAFwAXgAgAHJAYgB9BSSAQY0LjE4LjGYAQCgAQGqAQdnd3Mtd2l6sAEKwAEB&sclient=psy-ab&ved=0ahUKEwid59r8xbXsAhVBxIsKHbMeDUsQ4dUDCA0&uact=5
    - active: true
      last_visited: '2020-10-15T05:29:38'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: fault detection isolation and recovery - Google Search
      url: https://www.google.com/search?sxsrf=ALeKk00eyhNZZo62uWsn3_wYIz83FJyI5Q%3A1602728874194&ei=qrOHX7mxC-2vrgTKk7nQCQ&q=fault+detection+isolation+and+recovery&oq=fault+detection+iso&gs_lcp=CgZwc3ktYWIQAxgAMgUIABDJAzIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjoECAAQRzoECCMQJzoJCAAQyQMQFhAeOggIABAWEAoQHjoHCCMQ6gIQJzoECC4QJzoICAAQyQMQkQI6BQgAEJECOgIIADoCCC46BwguECcQkwI6BAgAEEM6CAguEMcBEK8BUOXOBViMhQZgzZwGaAFwAngEgAHLBIgBrRqSAQsxMC4xMi40LTEuMZgBAKABAaoBB2d3cy13aXqwAQrIAQTAAQE&sclient=psy-ab
      zoom: 1.0
  - history:
    - last_visited: '2020-10-15T04:00:33'
      pinned: false
      title: reaper projects git - Google Search
      url: https://www.google.com/search?q=reaper%20projects%20git
    - active: true
      last_visited: '2020-10-15T06:58:37'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: предшествующий - Google Search
      url: https://www.google.com/search?sxsrf=ALeKk02ga8dwlmKlt0RqjR6R3t8I7auEfQ%3A1602723632042&ei=MJ-HX8-KAqL5qwGJtplQ&q=%D0%BF%D1%80%D0%B5%D0%B4%D1%88%D0%B5%D1%81%D1%82%D0%B2%D1%83%D1%8E%D1%89%D0%B8%D0%B9&oq=%D0%BF%D1%80%D0%B5%D0%B4%D1%88%D0%B5%D1%81%D1%82%D0%B2%D1%83%D1%8E%D1%89%D0%B8%D0%B9&gs_lcp=CgZwc3ktYWIQAzIFCAAQyQMyAggAMgQIABAeMgQIABAeMgQIABAeMgQIABAeMgQIABAeMgQIABAeMgQIABAeMgQIABAeOgQIABBHOgUIIRCgAToHCCMQ6gIQJzoECCMQJzoGCCMQJxATOggILhDHARCjAjoLCC4QxwEQowIQyQM6AgguUI_AiwVYooCMBWD4iIwFaAFwAngEgAFiiAHODJIBAjE5mAEAoAEBqgEHZ3dzLXdperABCsgBBcABAQ&sclient=psy-ab&ved=0ahUKEwjP4ormsrXsAhWi_CoKHQlbBgoQ4dUDCA0&uact=5
      zoom: 1.0
  - history:
    - last_visited: '2020-10-18T14:04:50'
      pinned: false
      title: relationship between design patterns and state machines - Google Search
      url: https://www.google.com/search?q=relationship%20between%20design%20patterns%20and%20state%20machines
    - active: true
      last_visited: '2020-10-14T20:37:55'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: architecture - What is the difference between a state machine and the
        implementation of the state pattern? - Stack Overflow
      url: https://stackoverflow.com/questions/19859531/what-is-the-difference-between-a-state-machine-and-the-implementation-of-the-sta
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-10-14T20:37:55'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Designing A Calculator with FSM Logic | by Robert Vunabandi | Medium
      url: https://medium.com/@rvunabandi/making-a-calculator-in-javascript-64193ea6a492
      zoom: 1.5
  - history:
    - active: true
      last_visited: '2020-10-14T20:37:55'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'State Machine Design pattern — Part 2: State Pattern vs. State Machine
        | by Kousik Nath | Data Driven Investor | Medium'
      url: https://medium.com/datadriveninvestor/state-machine-design-pattern-part-2-state-pattern-vs-state-machine-3010dd0fcf28
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-10-14T20:37:55'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 4-1 A calculator as a finite state automaton
      url: https://www.cs.rit.edu/~ats/java/html/skript/4__01.htmld/index.html
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-10-14T20:37:55'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Binding - Wikipedia
      url: https://en.wikipedia.org/wiki/Binding
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-10-15T03:52:53'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: how to spell 122 - Google Search
      url: https://www.google.com/search?q=how%20to%20spell%20122
      zoom: 1.0
