windows:
- active: true
  geometry: !!binary |
    AdnQywACAAAAAAUAAAAAAAAADH8AAAQfAAAFAwAAAAMAAAx8AAAEHAAAAAIAAAAAB4A=
  tabs:
  - history:
    - last_visited: '2020-10-18T08:43:18'
      pinned: false
      title: Xwrits Manual
      url: http://www.lcdf.org/xwrits/man.html
    - last_visited: '2020-10-18T09:16:06'
      pinned: false
      title: History
      url: qute://history/
    - active: true
      last_visited: '2020-10-14T18:41:05'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: (67) Build A Calculator With JavaScript Tutorial - YouTube
      url: https://www.youtube.com/watch?v=j59qQ7YWLxw&feature=youtu.be
      zoom: 1.0
    - last_visited: '2020-10-15T23:42:14'
      pinned: false
      title: (64) ITT 2016 - Kevlin Henney - Seven Ineffective Coding Habits of Many
        Programmers - YouTube
      url: https://www.youtube.com/watch?v=ZsHMHukIlJY
    - last_visited: '2020-10-15T22:38:52'
      pinned: false
      title: (64) The Forgotten Art of Structured Programming - Kevlin Henney [C++
        on Sea 2019] - YouTube
      url: https://www.youtube.com/watch?v=SFv8Wm2HdNM
  - history:
    - last_visited: '2020-10-15T12:22:03'
      pinned: false
      title: termial ctrl s sleep - Google Search
      url: https://www.google.com/search?q=termial%20ctrl%20s%20sleep
    - active: true
      last_visited: '2020-10-14T18:41:15'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: microsoft natural ergonomic 4000 software - Google Search
      url: https://www.google.com/search?sxsrf=ALeKk01uu1KHmPNo82v3HC7EEnl0rizTig%3A1602667321561&ei=OcOGX_PTIfH2qwHq6rCgCg&q=microsoft+natural+ergonomic+4000+software&oq=microsoft+natural+ergonomic+4000+software&gs_lcp=CgZwc3ktYWIQAzIJCAAQyQMQFhAeMgYIABAWEB46BwgjEOoCECc6BwguEOoCECc6CAgAEMkDEJECOgUIABCRAjoCCC46AggAOggILhDHARCjAjoECCMQJzoECAAQQzoECC4QQzoFCAAQyQM6BwgjELACECc6BwgAEMkDEA06BAgAEA1Qzc0cWJeNH2CnkR9oBnAAeACAAacBiAGeIZIBBTMzLjEzmAEAoAEBqgEHZ3dzLXdperABCsABAQ&sclient=psy-ab&ved=0ahUKEwiz1JOD4bPsAhVx-yoKHWo1DKQQ4dUDCA0&uact=5
      zoom: 1.0
  - history:
    - last_visited: '2020-10-15T12:30:38'
      original-url: https://www.google.com/search?sxsrf=ALeKk01uu1KHmPNo82v3HC7EEnl0rizTig%3A1602667321561&ei=OcOGX_PTIfH2qwHq6rCgCg&q=microsoft+natural+ergonomic+4000+software&oq=microsoft+natural+ergonomic+4000+software&gs_lcp=CgZwc3ktYWIQAzIJCAAQyQMQFhAeMgYIABAWEB46BwgjEOoCECc6BwguEOoCECc6CAgAEMkDEJECOgUIABCRAjoCCC46AggAOggILhDHARCjAjoECCMQJzoECAAQQzoECC4QQzoFCAAQyQM6BwgjELACECc6BwgAEMkDEA06BAgAEA1Qzc0cWJeNH2CnkR9oBnAAeACAAacBiAGeIZIBBTMzLjEzmAEAoAEBqgEHZ3dzLXdperABCsABAQ&sclient=psy-ab&ved=0ahUKEwiz1JOD4bPsAhVx-yoKHWo1DKQQ4dUDCA0&uact=5#
      pinned: false
      title: microsoft natural ergonomic 4000 software - Google Search
      url: https://www.google.com/search?sxsrf=ALeKk01uu1KHmPNo82v3HC7EEnl0rizTig%3A1602667321561&ei=OcOGX_PTIfH2qwHq6rCgCg&q=microsoft+natural+ergonomic+4000+software&oq=microsoft+natural+ergonomic+4000+software&gs_lcp=CgZwc3ktYWIQAzIJCAAQyQMQFhAeMgYIABAWEB46BwgjEOoCECc6BwguEOoCECc6CAgAEMkDEJECOgUIABCRAjoCCC46AggAOggILhDHARCjAjoECCMQJzoECAAQQzoECC4QQzoFCAAQyQM6BwgjELACECc6BwgAEMkDEA06BAgAEA1Qzc0cWJeNH2CnkR9oBnAAeACAAacBiAGeIZIBBTMzLjEzmAEAoAEBqgEHZ3dzLXdperABCsABAQ&sclient=psy-ab&ved=0ahUKEwiz1JOD4bPsAhVx-yoKHWo1DKQQ4dUDCA0&uact=5
    - last_visited: '2020-10-15T12:30:59'
      pinned: false
      title: microsoft natural ergonomic 4000 software - Google Search
      url: https://www.google.com/search?sxsrf=ALeKk02btpAsCXfg9nu5nxkYvTOotV1Lgg%3A1602667833647&ei=OcWGX8H6Js_3qwHk_JboDQ&q=microsoft+natural+ergonomic+4000+software&oq=microsoft+natural+ergonomic+4000+software&gs_lcp=CgZwc3ktYWIQAzIHCCMQyQMQJzIGCAAQFhAeOgoIIxCwAhDJAxAnOggIABAIEA0QHjoHCCEQChCgAVCHX1iIggFgxpcBaAFwAXgAgAGaAYgB0QKSAQMxLjKYAQCgAQGqAQdnd3Mtd2l6wAEB&sclient=psy-ab&ved=0ahUKEwiB-6r34rPsAhXP-yoKHWS-Bd0Q4dUDCA0&uact=5
    - last_visited: '2020-10-15T12:31:04'
      pinned: false
      title: Natural Ergonomic Keyboard 4000 | Device downloads | Microsoft Accessories
      url: https://www.microsoft.com/accessories/en-ca/d/natural-ergonomic-keyboard-4000
    - active: true
      last_visited: '2020-10-14T18:41:06'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 404 Error
      url: https://www.microsoft.com/accessories/en-ca/d/natural-ergonomic-keyboard-3999
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-10-14T18:41:14'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: microsoft natural ergonomic 4000 spacebar is tough - Google Search
      url: https://www.google.com/search?q=microsoft%20natural%20ergonomic%204000%20spacebar%20is%20tough
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-10-14T18:41:05'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'SOLVED: Spacebar on my Microsoft Natural Ergonomic - Fixya'
      url: https://www.fixya.com/support/t9477876-spacebar_microsoft_natural
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-10-14T18:41:04'
      original-url: http://www.paulstravelpictures.com/MS-Natural-Ergo-Keyboard-Sticky-Spacebar-Fix/index.html
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: MS Natural Ergo Keyboard 4000 Stiff/Sticky Space Bar Problem Solutions
        - Pictures Illustrated Repair Guide
      url: https://www.paulstravelpictures.com/MS-Natural-Ergo-Keyboard-Sticky-Spacebar-Fix/index.html
      zoom: 1.75
  - history:
    - active: true
      last_visited: '2020-10-14T18:41:14'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: microsoft natural ergonomic 4000 spacebar metal sway bar - Google Search
      url: https://www.google.com/search?q=microsoft%20natural%20ergonomic%204000%20spacebar%20metal%20sway%20bar
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-10-14T18:41:05'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'The Unauthorized Version: Fix for Microsoft Natural Ergo Keyboard 4000
        Stiff Spacebar'
      url: http://dthatcher.blogspot.com/2011/06/fix-for-microsoft-natural-ergo-keyboard.html
      zoom: 1.75
  - history:
    - last_visited: '2020-10-15T04:57:15'
      pinned: false
      title: (67) A First Look At SpaceVim - YouTube
      url: https://www.youtube.com/watch?v=iXPS_NHLj9k
    - last_visited: '2020-10-15T05:24:17'
      pinned: false
      title: (67) YouTube
      url: https://www.youtube.com/
    - active: true
      last_visited: '2020-10-14T18:41:05'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: '(67) 2017 Personality 02/03: Historical & Mythological Context - YouTube'
      url: https://www.youtube.com/watch?v=HbAZ6cFxCeY
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-10-14T18:41:05'
      pinned: false
      scroll-pos:
        x: 0
        y: 2100
      title: Disable Keyboard Repeat from command line? - Ask Ubuntu
      url: https://askubuntu.com/questions/576421/disable-keyboard-repeat-from-command-line
      zoom: 1.0
  - history:
    - last_visited: '2020-10-17T14:04:50'
      pinned: false
      title: relationship between design patterns and state machines - Google Search
      url: https://www.google.com/search?q=relationship%20between%20design%20patterns%20and%20state%20machines
    - active: true
      last_visited: '2020-10-14T18:41:05'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: architecture - What is the difference between a state machine and the
        implementation of the state pattern? - Stack Overflow
      url: https://stackoverflow.com/questions/19859531/what-is-the-difference-between-a-state-machine-and-the-implementation-of-the-sta
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-10-14T18:41:05'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Designing A Calculator with FSM Logic | by Robert Vunabandi | Medium
      url: https://medium.com/@rvunabandi/making-a-calculator-in-javascript-64193ea6a492
      zoom: 1.5
  - history:
    - active: true
      last_visited: '2020-10-14T18:41:04'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'State Machine Design pattern — Part 2: State Pattern vs. State Machine
        | by Kousik Nath | Data Driven Investor | Medium'
      url: https://medium.com/datadriveninvestor/state-machine-design-pattern-part-2-state-pattern-vs-state-machine-3010dd0fcf28
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-10-14T18:41:05'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 4-1 A calculator as a finite state automaton
      url: https://www.cs.rit.edu/~ats/java/html/skript/4__01.htmld/index.html
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-10-14T18:41:05'
      pinned: false
      scroll-pos:
        x: 0
        y: 15573
      title: xkeysnail/key.py at master · mooz/xkeysnail
      url: https://github.com/mooz/xkeysnail/blob/master/xkeysnail/key.py
      zoom: 1.75
  - history:
    - active: true
      last_visited: '2020-10-14T18:44:22'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: xkeysnail remap menu key - Google Search
      url: https://www.google.com/search?q=xkeysnail%20remap%20menu%20key
      zoom: 1.0
  - active: true
    history:
    - active: true
      last_visited: '2020-10-14T18:44:28'
      pinned: false
      scroll-pos:
        x: 0
        y: 800
      title: xorg - How to remap the Context Menu key to the Super key - Unix & Linux
        Stack Exchange
      url: https://unix.stackexchange.com/questions/13369/how-to-remap-the-context-menu-key-to-the-super-key
      zoom: 1.0
  - history:
    - last_visited: '2020-10-15T07:12:24'
      pinned: false
      title: np.log(Pop1831) - Google Search
      url: https://www.google.com/search?q=np.log%28Pop1831%29
    - active: true
      last_visited: '2020-10-14T18:41:05'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: python - Can some one explain me what does np.log do? - Stack Overflow
      url: https://stackoverflow.com/questions/28058527/can-some-one-explain-me-what-does-np-log-do
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-10-14T18:41:04'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Binding - Wikipedia
      url: https://en.wikipedia.org/wiki/Binding
      zoom: 1.0
