windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAAAAAAAAAABXcAAAQAAAAAAwAAAAMAAAV0AAAD/QAAAAEAAAAABXgAAAADAAAA
    AwAABXQAAAP9
  tabs:
  - history:
    - active: true
      last_visited: '2021-06-01T17:33:37'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: "▸ \U0001D40C\U0001D42E\U0001D41B\U0001D428\U0001D427\U0001D420 \U0001D40F\U0001D41A\U0001D42B\U0001D424┊박무봉
        | Wiki | Anime Amino"
      url: https://aminoapps.com/c/anime/page/item/mubong-park-bagmubong/jPto_IGomkgGr4zg420wvwVkgRVGN
      zoom: 1.3
  - history:
    - active: true
      last_visited: '2021-06-01T17:33:35'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Utaite | Utaite Wiki | Fandom
      url: https://utaite.fandom.com/wiki/Utaite
      zoom: 1.3
  - history:
    - active: true
      last_visited: '2021-06-01T17:33:38'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: aspiring utaites - Google Search
      url: https://www.google.com/search?q=aspiring+utaites&sxsrf=ALeKk02aJ6AuwfHkUW5oZ9d4i7WWV4NCqA%3A1622184199369&ei=B5GwYOfvFcitrgSR0I6AAg&oq=aspiring+utaites&gs_lcp=Cgdnd3Mtd2l6EAMyBQghEKABOgQIIxAnOgQIABBDOgIIADoECAAQCjoECC4QCjoHCCMQsAIQJzoGCAAQDRAKOgQIABANOgYIABANEB46CAgAEA0QChAeOgYIABAHEB46CAgAEAcQChAeOgoIABAIEAcQChAeUL0WWPfsAWCw8QFoAXACeAGAAecBiAGuDJIBBjEwLjQuMZgBAKABAaoBB2d3cy13aXrAAQE&sclient=gws-wiz&ved=0ahUKEwinj9qH4-vwAhXIlosKHRGoAyAQ4dUDCA4&uact=5
      zoom: 1.3
  - history:
    - active: true
      last_visited: '2021-06-01T17:33:35'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: (2) Who is your favorite Utaite? - Quora
      url: https://www.quora.com/Who-is-your-favorite-Utaite
      zoom: 1.3
  - history:
    - active: true
      last_visited: '2021-06-01T17:33:36'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Manage your dotfiles with Ansible | by Kyle Espinola | Espinola Designs
        | Medium
      url: https://medium.com/espinola-designs/manage-your-dotfiles-with-ansible-6dbedd5532bb
      zoom: 1.3
  - history:
    - active: true
      last_visited: '2021-06-01T17:33:35'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'Patterns: targeting hosts and groups — Ansible Documentation'
      url: https://docs.ansible.com/ansible/latest/user_guide/intro_patterns.html
      zoom: 1.3
  - history:
    - active: true
      last_visited: '2021-06-01T17:33:35'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Glossary — Ansible Documentation
      url: https://docs.ansible.com/ansible/latest/reference_appendices/glossary.html
      zoom: 1.3
  - history:
    - active: true
      last_visited: '2021-06-01T17:33:35'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 96Neko | Utaite Wiki | Fandom
      url: https://utaite.fandom.com/wiki/96Neko
      zoom: 1.3
  - history:
    - active: true
      last_visited: '2021-06-01T17:33:37'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: learn kanji online - Google Search
      url: https://www.google.com/search?q=learn%20kanji%20online
      zoom: 1.3
  - history:
    - active: true
      last_visited: '2021-06-01T17:33:36'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: WaniKani, a kanji learning application by Tofugu
      url: https://www.wanikani.com/#explanation
      zoom: 1.3
  - history:
    - active: true
      last_visited: '2021-06-01T17:33:37'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: wanikani - Google Search
      url: https://www.google.com/search?q=wanikani
      zoom: 1.3
  - active: true
    history:
    - active: true
      last_visited: '2021-06-01T17:33:35'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Is WaniKani Free? | WaniKani Knowledge
      url: https://knowledge.wanikani.com/getting-started/payment-and-billing/wanikani/wanikani-free/
      zoom: 1.3
