windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAAAAAAAAAABXcAAAQBAAAAAwAAAAMAAAV0AAAD/gAAAAEAAAAABXgAAAADAAAA
    AwAABXQAAAP+
  tabs:
  - history:
    - active: true
      last_visited: '2020-12-01T00:35:36'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: The Modern JavaScript Tutorial
      url: https://javascript.info/
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-12-01T00:35:36'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'Conditional branching: if, ''?'''
      url: https://javascript.info/ifelse
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-12-01T00:35:38'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Learn
      url: https://learn.epam.com/start
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-12-01T00:35:36'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Sign In to EPAM
      url: https://access.epam.com/auth/realms/plusx/protocol/openid-connect/auth?client_id=learnId&redirect_uri=https%3A%2F%2Flearn.epam.com%2Fauth%2Fsignin-iam&response_type=code&scope=openid%20profile%20email%20offline_access&code_challenge=0dkfoIQfDCeu6vcXLWm5cFv4A_KSrVOydAmDlckQ5ac&code_challenge_method=S256&nonce=637417967132327240.MTk4OTI0NzgtNDc0OC00MmQzLTk2ODItOWZjMTM4ZDg2NTNiNTFjODM5ZjEtM2M0Yi00ZTllLTg0NmYtMzIwNzgzOGQwZDEz&state=CfDJ8IajQ5NwKntKsOi58laDrEzO3ibY09I_MEHGktyHD53D-3VzSi4DAb4bUnhHS8z4XT6M1NoOqpnqqaqVaKtZs8G080lyXDCXxwhuoQdzxe8En5rMrLaXpnu1q68roVeVlxn_kvPixjijP-iJMI0In6cWmUuAdTVGyf-zrlZeeVoItC7QofmcuAVrFdP8Yfjevcrszt7zGPYdPrx82ouOro7XrHoC4IVL8kUZypvt5tIsa_eu-OhJC02XPM59ghfx9F82GrYQl3usruIOV2jNZTvTd2uiqI0O3fgcnyA_y7hNM0iRbEC5Y6SSPNF3RKXGaLUCiykTuX9SHNAZYEWMq751gtt7D4QQQNwPcN3fX05EkzSAjMlP9MuaBRb7Ib_fWf6gB1c47EB1PYUEC_MdXrxyUd_xA7dsH2ee2WhpqELP-WIBW9eJPUUZPpmzG_x-DapkJ2XuUfONS9DRTidx4V4&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=5.5.0.0
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-12-01T00:35:36'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Sign In to EPAM
      url: https://access.epam.com/auth/realms/plusx/protocol/openid-connect/auth?nonce=DqiL9u7IJ700myXupYWdsDKvkQaRiepiE7ccJu2ZVJy2hAnAKaL0bSagATUoo9gT&state=XOgsYmOccT8JhRalTq6Tj5JEPF9bGsL9&redirect_uri=https://elearn.epam.com/auth/complete/extended-openid-connect/&response_type=code&client_id=learnId&scope=openid+profile+email
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-12-01T00:35:36'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Node (networking) - Wikipedia
      url: https://en.wikipedia.org/wiki/Node_(networking)
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-12-01T00:35:36'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: IPv4 - Wikipedia
      url: https://en.wikipedia.org/wiki/IPv4#Identification
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-12-01T00:35:36'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Classful network - Wikipedia
      url: https://en.wikipedia.org/wiki/Classful_network
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-12-01T00:35:36'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Internet Protocol - Wikipedia
      url: https://en.wikipedia.org/wiki/Internet_Protocol
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-12-01T00:56:56'
      pinned: false
      scroll-pos:
        x: 0
        y: 1666
      title: Transmission Control Protocol - Wikipedia
      url: https://en.wikipedia.org/wiki/Transmission_Control_Protocol
      zoom: 1.5
  - active: true
    history:
    - last_visited: '2020-12-01T01:03:13'
      pinned: false
      title: (110) bob kahn - YouTube
      url: https://www.youtube.com/results?q=bob+kahn
    - last_visited: '2020-12-01T01:03:13'
      pinned: false
      title: (110) bob kahn tcp - YouTube
      url: https://www.youtube.com/results?search_query=bob+kahn+tcp
    - active: true
      last_visited: '2020-12-01T01:03:53'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: '(110) Robert Elliot "Bob" Kahn: ARPNET TCP/IP - YouTube'
      url: https://www.youtube.com/watch?v=JG5-P1jZVxY
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2020-12-01T01:02:34'
      pinned: false
      scroll-pos:
        x: 0
        y: 1359
      title: (110) vint cerf - YouTube
      url: https://www.youtube.com/results?q=vint+cerf
      zoom: 1.0
    - last_visited: '2020-12-01T01:00:33'
      pinned: false
      title: (110) Vint Cerf explains...Who runs the Internet's address book? - YouTube
      url: https://www.youtube.com/watch?v=vd3dH90tdhk
  - history:
    - active: true
      last_visited: '2020-12-01T00:35:36'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Port (computer networking) - Wikipedia
      url: https://en.wikipedia.org/wiki/Port_(computer_networking)#:~:text=In%20computer%20networking%2C%20a%20port,a%20type%20of%20network%20service.
      zoom: 1.0
- geometry: !!binary |
    AdnQywADAAAAAAV4AAAAAAAADPcAAAQfAAAFewAAAAMAAAz0AAAEHAAAAAIAAAAAB4AAAAV7AAAA
    AwAADPQAAAQc
  tabs:
  - active: true
    history:
    - active: true
      last_visited: '2020-12-01T00:35:37'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: My ~TiddlyWiki — a non-linear personal web notebook
      url: http://127.0.0.1:8081/
      zoom: 1.0
