#!/usr/bin/env bash

_rofi () {
    rofi -theme solarized -dmenu -i -no-levenshtein-sort -width 1000 "$@"
}

# display settings
display_type=2
max_str_width=80

# keybindings
switch_view="Alt+Tab"
new_bookmark="Alt+m"
actions="Alt+a"
edit="Alt+e"
delete="Alt+d"

# colors
help_color="#2d7ed8"
